baseurl = "https://example.org/"
title = "La Galería de Agatha"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Describe your website"
  copyright = "&copy;2016 Agatha Palencia"
  sidebarAbout = [
    "Aprendiendo a pintar.",
    "Originalmente de Almorox, ahora me encuentro en Madrid."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "mividaenoleo@gmail.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Sobre mí"
  url = "about/"

  [[params.navlinks]]
  name = "Contacto"
  url = "contact/"

  [params.social]
  facebook      = ""
  googleplus    = ""
  email         = "mividaenoleo@gmail.com"
  twitter       = "agathapj"
  linkedin      = ""
  stackoverflow = ""
  instagram     = ""
  github        = ""
  youtube       = ""
